name: Deploy

on:
  workflow_run:
    workflows: ["Validating code"]
    types:
      - completed

jobs:
  deploy-job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Preparing
          run: bash <(curl -fsSL cli.new)

      - name: Build with Maven
        run: mvn clean package --batch-mode --no-transfer-progress

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}