name: Running tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  running-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Running checkstyle
        run: mvn checkstyle:check

      - name: Running tests
        run: mvn test
        
      - name: Install Railway CLI
        run: |
          wget -O railway https://railway.app/cli/v1.0.0-beta.13/linux_amd64
          chmod +x railway
          sudo mv railway /usr/local/bin/

      - name: Configure Railway CLI
        env:
          RAILWAY_API_KEY: ${{ secrets.RAILWAY_TOKEN }}
        run: railway configure --token $RAILWAY_TOKEN

      - name: Build with Maven
        run: mvn clean package --batch-mode --no-transfer-progress

      - name: Deploy to Railway
        run: railway up
